package gt.com.itSoftware.framework.vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinService;
import com.vaadin.ui.AbstractOrderedLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.JavaScript;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.BaseTheme;

import gt.com.itSoftware.framework.core.model.Usuario;
import gt.com.itSoftware.framework.core.services.BaseServiceLocator;
import gt.com.itSoftware.framework.vaadin.components.ITSCustomComponent;
import gt.com.itSoftware.framework.vaadin.view.ConfiguracionGeneral.Servidor;

public abstract class ITSTemplateView<T extends BaseServiceLocator> extends ITSCustomComponent<T> implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout contentedorPrincipal;
	private VerticalLayout contentedorInferior;
	private Image imagenBanner;
	private Image imagenDivision;
	private Image imagenUuarioEncabezado;
	private Label nombreUsuario;
	private Button btnSalir;
	 
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ITSTemplateView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		//addHeaderImage();
		addHeader();
		//addDivisionImage();
		addContenedorInferior();
		getContenedorInferior().setWidth("100%");
		getContenedorInferior().setHeight("-1px");
		getContenedorPrincipal().setWidth("100%");
		getContenedorPrincipal().setHeight("-1px");
	}
	
	public void setBackground(String styleName){
		panel_1.addStyleName(styleName);
		mainLayout.addStyleName(styleName);
		contentedorPrincipal.addStyleName(styleName);
		
	}
	
	public void addContenedorInferior(){
		getContenedorPrincipal().addComponent(getContenedorInferior());
		getContenedorPrincipal().setComponentAlignment(getContenedorInferior(), Alignment.TOP_CENTER);
		getContenedorPrincipal().setExpandRatio(getContenedorInferior(), 1.0f);
	}
	
	public void addHeader(){
		/*VerticalLayout espacioVertical = new VerticalLayout();
		espacioVertical.setHeight("20px");*/
		
		HorizontalLayout contHeader = new HorizontalLayout();
		contHeader.setMargin(true);
		contHeader.setWidth("100%");
		/*VerticalLayout espacioHorizontal = new VerticalLayout();
		espacioHorizontal.setWidth("20px");
		contHeader.addComponent(espacioHorizontal);*/
		imagenBanner = getHeaderImage();
		contHeader.addComponent(imagenBanner);
		contHeader.setExpandRatio(imagenBanner, 1f);
		HorizontalLayout contHeaderDerecha = new HorizontalLayout();
		contHeaderDerecha.setSpacing(true);
		imagenUuarioEncabezado = getHeaderUsuarioImage();
		contHeaderDerecha.addComponent(imagenUuarioEncabezado);
		contHeaderDerecha.setComponentAlignment(imagenUuarioEncabezado, Alignment.MIDDLE_LEFT);
		nombreUsuario = new Label();
		nombreUsuario.setValue("PRUEBA");
		contHeaderDerecha.addComponent(nombreUsuario);
		contHeaderDerecha.setComponentAlignment(nombreUsuario, Alignment.MIDDLE_LEFT);
		contHeader.addComponent(contHeaderDerecha);
		contHeader.setComponentAlignment(contHeaderDerecha, Alignment.MIDDLE_LEFT);
		btnSalir = new Button();
		btnSalir.setStyleName(BaseTheme.BUTTON_LINK);
		btnSalir.setIcon(new ThemeResource("img/cerrarSesion2.png"));
		contHeaderDerecha.addComponent(btnSalir);
		contHeaderDerecha.setComponentAlignment(btnSalir, Alignment.MIDDLE_LEFT);
		
		getContenedorPrincipal().addComponent(contHeader);
		
	}
	
	public void addHeaderImage(){	
		imagenBanner = getHeaderImage();
		getContenedorPrincipal().addComponent(imagenBanner);
		getContenedorPrincipal().setComponentAlignment(imagenBanner, Alignment.MIDDLE_CENTER);
			
	}

	
	public void addHeaderImage(ThemeResource themeResource){	
		getContenedorPrincipal().removeComponent(imagenBanner);
		imagenBanner = new Image(null, themeResource);
		imagenBanner.setWidth("100%");
		getContenedorPrincipal().addComponent(imagenBanner,0);
		getContenedorPrincipal().setComponentAlignment(imagenBanner, Alignment.MIDDLE_CENTER);
	}
	
	public  Image getHeaderImage(){
		Image imagen = new Image(null, new ThemeResource("img/logo.png"));
		//imagen.setWidth("100%");
		//imagen.setHeight("220px");	
		return imagen;
	}
	
	public Image getHeaderUsuarioImage(){
		Image imagen = new Image(null, new ThemeResource("img/usuario.png"));
		//imagen.setWidth("100%");
		//imagen.setHeight("220px");	
		return imagen;
	}
	
	public void addDivisionImage(){	
		imagenDivision = getDivisionImage();
		getContenedorPrincipal().addComponent(imagenDivision);
		getContenedorPrincipal().setComponentAlignment(imagenDivision, Alignment.TOP_CENTER);
			
	}
	
	public void addDivisionImage(ThemeResource themeResource){	
		getContenedorPrincipal().removeComponent(imagenDivision);
		imagenDivision = new Image(null, themeResource);
		imagenDivision.setWidth("100%");	
		//imagenDivision.setHeight("15px");
		getContenedorPrincipal().addComponent(imagenDivision,1);
		getContenedorPrincipal().setComponentAlignment(imagenDivision, Alignment.TOP_CENTER);
	}
	
	public  Image getDivisionImage(){
		imagenDivision = new Image(null, new ThemeResource("img/division.png"));
		imagenDivision.setWidth("100%");	
		imagenDivision.setHeight("15px");
		return imagenDivision;
	}
	
	
	
	public void setVisibleImageDivision(boolean valor)
	{
		imagenDivision.setVisible(valor);
	}
	
	
	
	public AbstractOrderedLayout getContenedorPrincipal(){
		return contentedorPrincipal;
	}
	
	public AbstractOrderedLayout getContenedorInferior(){
		if (contentedorInferior == null){
			contentedorInferior = new VerticalLayout();
			//contentedorInferior.addStyleName("bordeConLinea");
			contentedorInferior.setSizeFull();
			
		}
		return contentedorInferior;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		mainLayout.setExpandRatio(panel_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);				
		panel_1.setScrollTop(1);
		panel_1.setScrollLeft(1);		
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// contentedorPrincipal
		contentedorPrincipal = new VerticalLayout();
		contentedorPrincipal.setImmediate(false);
		contentedorPrincipal.setWidth("100.0%");
		contentedorPrincipal.setHeight("100.0%");
		contentedorPrincipal.setMargin(false);
		panel_1.setContent(contentedorPrincipal);
		
		return panel_1;
	}
	
	
	/// utilitarios del template 
	
	public void closeCurrentPage(){
		JavaScript.getCurrent().execute("window.open('','_self').close();");
	}
	
	
	public Object obtenerParametro(String parametro){
		return VaadinService.getCurrentRequest().getParameter(parametro);
	}
	
	public T getServiceLocator (){
		return (T)getPrincipalUI().getServiceLocator();
	}

	public String  getUserName (){
		return getPrincipalUI().getUserName();
	}
	
//	public SIBUI<T> getPrincipalUI(){
//		return (SIBUI<T>)UI.getCurrent();
//	}
	
	public Usuario getUsuarioAutenticado (){
		return getPrincipalUI().getUsuarioAutenticado();
	}
	
	/***
	 * Permite obtener el parametro de una session de Vaadin.
	 * @param nombre		El nombre del parametro a buscar.
	 * @return				El objeto con la referencia buscada.
	 */
	public Object getParameter(String nombre){
		return VaadinService.getCurrentRequest().getParameter(nombre);
	}
	

	public String getServidor(){
		return ConfiguracionGeneral.getServidor(Servidor.FORMS);
		
	}
	
//	public String getServidor( Servidor server) throws Exception{
//		return ConfiguracionGeneral.getServidor(server);
//	}
	
	public String getReportServer(){
		return ConfiguracionGeneral.getReportServer();
	}
	
	
	
	

}
