package gt.com.itSoftware.framework.vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinService;
import com.vaadin.ui.AbstractOrderedLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.JavaScript;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@Deprecated
public abstract class TemplateView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout contentedorPrincipal;
	private VerticalLayout contentedorInferior;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TemplateView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		addHeaderImage();
		addDivisionImage();
		addContenedorInferior();
		getContenedorInferior().setSizeUndefined();			
		getContenedorPrincipal().setSizeUndefined();
				
	}

	
	
	
	public void setBackground(String styleName){
		panel_1.addStyleName(styleName);
		mainLayout.addStyleName(styleName);
		contentedorPrincipal.addStyleName(styleName);
		
	}
	
	public void addContenedorInferior(){
		getContenedorPrincipal().addComponent(getContenedorInferior());
		getContenedorPrincipal().setComponentAlignment(getContenedorInferior(), Alignment.TOP_CENTER);
		getContenedorPrincipal().setExpandRatio(getContenedorInferior(), 1.0f);
	}
	
	public void addHeaderImage(){	
		Image i = getHeaderImage();
		getContenedorPrincipal().addComponent(i);
		getContenedorPrincipal().setComponentAlignment(i, Alignment.MIDDLE_CENTER);
			
	}
	
	public  Image getHeaderImage(){
		Image imagen = new Image(null, new ThemeResource("img/banner.png"));
		imagen.setWidth("100%");
		//imagen.setHeight("220px");	
		return imagen;
	}
	
	public void addDivisionImage(){	
		Image i = getDivisionImage();
		getContenedorPrincipal().addComponent(i);
		getContenedorPrincipal().setComponentAlignment(i, Alignment.TOP_CENTER);
			
	}
	
	public  Image getDivisionImage(){
		Image imagen = new Image(null, new ThemeResource("img/division.png"));
		imagen.setWidth("100%");	
		imagen.setHeight("15px");
		return imagen;
	}
	
	
	
	public AbstractOrderedLayout getContenedorPrincipal(){
		return contentedorPrincipal;
	}
	
	public AbstractOrderedLayout getContenedorInferior(){
		if (contentedorInferior == null){
			contentedorInferior = new VerticalLayout();
			//contentedorInferior.addStyleName("bordeConLinea");
			contentedorInferior.setSizeFull();
			
		}
		return contentedorInferior;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		mainLayout.setExpandRatio(panel_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);				
		panel_1.setScrollTop(1);
		panel_1.setScrollLeft(1);		
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// contentedorPrincipal
		contentedorPrincipal = new VerticalLayout();
		contentedorPrincipal.setImmediate(false);
		contentedorPrincipal.setWidth("100.0%");
		contentedorPrincipal.setHeight("100.0%");
		contentedorPrincipal.setMargin(false);
		panel_1.setContent(contentedorPrincipal);
		
		return panel_1;
	}
	
	
	/// utilitarios del template 
	
	public void closeCurrentPage(){
		JavaScript.getCurrent().execute("window.open('','_self').close();");
	}
	
	
	public Object obtenerParametro(String parametro){
		return VaadinService.getCurrentRequest().getParameter(parametro);
	}
	
	
	
	
	

}
